hash-format = "sha256"

[[files]]
file = "mods/SubtleEffects-fabric-1.21.1-1.13.0.jar"
hash = "feafb38dd65f198189e470f97a638356434dfbf446b6d7d7256809ffe069528e"

[[files]]
file = "mods/Terrastorage-1.2.7+1.21-1.21.1.jar"
hash = "c0c044067bdb6540605c017149839530d884db3ca0c91ae656f1389e74a57ba3"

[[files]]
file = "mods/accessories.pw.toml"
hash = "7ab57cabb667d43350bec4e692425732520560f2000d0732c70d31826415c539"
metafile = true

[[files]]
file = "mods/almanac-lib.pw.toml"
hash = "6ec05c687ee2883e5a10d00bbc83f287d9d93946fc18a0d07abcc1324a4db249"
metafile = true

[[files]]
file = "mods/alternate-current.pw.toml"
hash = "dbe1649fa42770235a80d50b60f37c86221a1ecb3e0cd5a3eebc2f9167928f91"
metafile = true

[[files]]
file = "mods/amendments.pw.toml"
hash = "7df47bca45f8cc678cf5b32361db50653b98631e93ac9d201daa0124503a1a50"
metafile = true

[[files]]
file = "mods/anvil-never-too-expensive.pw.toml"
hash = "6d1f37975f08f1385035b8857d99eceaa8f407dbb66991984501774667f45fb1"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
hash = "9ce55dc09b4b2a28b39ae47d146cfe5399dfc74666d9ae53811bdef4058b3491"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "39792a11da59cebc770f3918dd0ad53637bcbd206dc19bfa6709392bfd2d1830"
metafile = true

[[files]]
file = "mods/armor-statues.pw.toml"
hash = "6710eac4f0afbf236eedcbca6304179defc933faf68608c83b3e02b215e507e2"
metafile = true

[[files]]
file = "mods/artifacts.pw.toml"
hash = "13c2d95d4c338e36661538ce7af798f5082c26131845f04ec0a39bb6e431c12f"
metafile = true

[[files]]
file = "mods/balm-fabric.pw.toml"
hash = "bac8c61791259d82ff90e2cd19f2f7f2ceea6aed9427fd8c3cce58401cd08d24"
metafile = true

[[files]]
file = "mods/betterf3.pw.toml"
hash = "5fe7e26e9534cf3d7829e8c4937c7b700d2084b6345aed901c1c3de9a80f49fa"
metafile = true

[[files]]
file = "mods/bookshelf.pw.toml"
hash = "ace316eb88ca635b9853219bedc484378beea13e3122d775979f91005483225c"
metafile = true

[[files]]
file = "mods/c2me.pw.toml"
hash = "ec813e6ade7e4f375d23908224581c1424d6bccaf3a54d9c59761c447c2707f9"
metafile = true

[[files]]
file = "mods/cardinal-components-api.pw.toml"
hash = "fc50ea07be81ba9ceacf1f3f3059b7e335dbc16ca258a146fbf93a23d97df9ff"
metafile = true

[[files]]
file = "mods/carry-on.pw.toml"
hash = "c4f294f47a114849b5510bba3da64503e7e714c6178dbe0edf5573065e5ef541"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "9e21cc4fae5ed88e306b4601c5e1533f883aa8b60c6e36dedeec82718be87059"
metafile = true

[[files]]
file = "mods/clumps.pw.toml"
hash = "8924f70537405b8bc884504814f8963483268b492bcad4c6d87badde63ee69e5"
metafile = true

[[files]]
file = "mods/common-network.pw.toml"
hash = "80f5d2a1cd44079299b36e44cf19936f6ee9cb37e5014554c811969b9fe2692b"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "b50378ddd8de5877ce51ded7616ebbf3ad0a5e18af8125a473411fbabc6c37cd"
metafile = true

[[files]]
file = "mods/coroutil.pw.toml"
hash = "74b82158cadd5d72b6f1c706aa7f190c4e791681472fc98735cec30acf622535"
metafile = true

[[files]]
file = "mods/darksleep.pw.toml"
hash = "ce3aea75c10c6590dc2655c3095e1a0fc69ac3adf01793cfb9dffe4a727795d0"
metafile = true

[[files]]
file = "mods/detail-armor-bar.pw.toml"
hash = "c218a67424771ec2b91e456bf5ae2549c699f98f9f21d87ec82b97a3e72b516b"
metafile = true

[[files]]
file = "mods/dis-enchanting-table.pw.toml"
hash = "a35abc9918ab470587cb18f05a37918a921ec0ae59f1c256ebec3c20d819904e"
metafile = true

[[files]]
file = "mods/double-slabs.pw.toml"
hash = "62e240258b02777c01cc4ee8fdff4b47a05f23c77d5794a111bb28c448436fe5"
metafile = true

[[files]]
file = "mods/dynamiclights-reforged.pw.toml"
hash = "1659cc97cceaa896f19efba42b2dd2b70797743f61da240e07d010f354aa4fef"
metafile = true

[[files]]
file = "mods/easy-anvils.pw.toml"
hash = "4d12c0266b95a0616377dc797b100ad0520977a8c97739cacfc2de2ac214e66c"
metafile = true

[[files]]
file = "mods/easy-magic.pw.toml"
hash = "765d72129bfb30756fee8e30e11fc04c6658292b5041a5890aa89e7013a387f9"
metafile = true

[[files]]
file = "mods/echo-chest.pw.toml"
hash = "a70697925dabb0bea3094d8e4163120dbc7662d681d9fb2d78ae55442920800c"
metafile = true

[[files]]
file = "mods/enchanted-vertical-slabs.pw.toml"
hash = "509f45132bafade5ef29314799319edb5161db9290b74d6f44e743535f505e7d"
metafile = true

[[files]]
file = "mods/enhanced-block-entities.pw.toml"
hash = "2c1d05da2179691fc1c27b53eaf942c32ff1528739a9be5e3a34dd2a92105696"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "0e28ba15ba1769864a4af0b2f7ffaa3c90017b49633bef2a843b14a46e9a791d"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "373c9e22de4d4df2997c0316cb244d3b61b1cc6a6c748c1593af757653b4f957"
metafile = true

[[files]]
file = "mods/farmers-delight-refabricated.pw.toml"
hash = "8afba585ee9c0cef8482a54d53669bd2536795ee6f406e46d8ae06314d874a62"
metafile = true

[[files]]
file = "mods/farmers-structures.pw.toml"
hash = "ca0ba1a8f714896e446e014027173530021dbe74857b5f7ca644e9975b30fb74"
metafile = true

[[files]]
file = "mods/fence-on-slab.pw.toml"
hash = "f4ea5ee124d20252148db5996ce58f3d777b05abd13ceabc0263745a2a23bc60"
metafile = true

[[files]]
file = "mods/forge-config-api-port-fabric.pw.toml"
hash = "a449489f9024a2333343558296f30ff4aeb35792b64f58c0bac927a1c82dfd53"
metafile = true

[[files]]
file = "mods/framework.pw.toml"
hash = "31fe856cfb4be0a169cd346540b5ba35c88107b19a15568a11112b38cebb2b62"
metafile = true

[[files]]
file = "mods/ftb-library-fabric.pw.toml"
hash = "9cff1433e8cbb02d9c9e744150a878293d5ae622a8da70670fb64e68b32e0839"
metafile = true

[[files]]
file = "mods/ftb-ultimine-fabric.pw.toml"
hash = "887fa762e49fc5733448942a17080287709a8e52c02f5a03bd4b4d0b076b92fc"
metafile = true

[[files]]
file = "mods/fzzy-config.pw.toml"
hash = "ae2dd2b605e120ec04be2accfeb20938ceb4551bcc683b8c1a0f725578ea293e"
metafile = true

[[files]]
file = "mods/geckolib.pw.toml"
hash = "eba84c0fa4bdcc4ebca816482af78ab50cba8362591d4354b490da8f563bbe89"
metafile = true

[[files]]
file = "mods/glitchcore.pw.toml"
hash = "7f5d08d2293bd01f6d00bc91cb060e2b7bb33d1b6b10956d0936b127e9c96165"
metafile = true

[[files]]
file = "mods/held-item-tooltips.pw.toml"
hash = "b2ab8b729fe9850da6108abd012dd810637e56bd10db83167f7e9678f1ad35f3"
metafile = true

[[files]]
file = "mods/hole-filler-mod.pw.toml"
hash = "b4255b08565aabd3720c90390335990e3f84f875588e60c32380a6d67c622d77"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "7cd0e909ee98d8387a1173356ca000fe958d15a3ebb58984def87dec663184f7"
metafile = true

[[files]]
file = "mods/irisshaders.pw.toml"
hash = "b31e45972ba08291e168f9d93ed14d679a8799983b7bce7ca38faa795a85bf3a"
metafile = true

[[files]]
file = "mods/iron-bookshelves.pw.toml"
hash = "3b682e26dd7be9b3f2cbaad9ab6f20955eb6554e13e76a0909ff101d1a579ee0"
metafile = true

[[files]]
file = "mods/iron-chests-for-fabric.pw.toml"
hash = "c3656a65bfd7ab4c2ebf4278939906386ec88165fbd24bc33fbc1c31470d1924"
metafile = true

[[files]]
file = "mods/jamlib.pw.toml"
hash = "f99d68db548845d3e5cad75d714429ea73deaa5d41d8d3404af8ca4eb74f1457"
metafile = true

[[files]]
file = "mods/jei.pw.toml"
hash = "7eb78a6b68fa0a024fd70bcfebc12cf97f7eab71987bc01e3ace54689d4d58ce"
metafile = true

[[files]]
file = "mods/journeymap.pw.toml"
hash = "3c81bed7d427dc00917641a8414f17b10053c624381c554b26270b34f0afeb6b"
metafile = true

[[files]]
file = "mods/let-me-despawn.pw.toml"
hash = "0111e250e04a831514a49464405579fb36b4b8b61dc15928e15a2a805dc569a0"
metafile = true

[[files]]
file = "mods/litematica-printer-inprim.pw.toml"
hash = "90f3a1e79a625c7bb68a13b23f88fdb4ab2b66ccbda4c5b83ffc33551e465be6"
metafile = true

[[files]]
file = "mods/litematica.pw.toml"
hash = "084365491a525dccd7a0274d5cb0a4b00af3dd4deb55ddcd53d0663783db426d"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "3fdc92ff58a76637e11877ce3855dfee8448390e471a7597b842e744574b1c95"
metafile = true

[[files]]
file = "mods/ly-veinminer-enchantment-v1.0.2.jar"
hash = "305ae02dcc74be6e2105d4e95e6c398122dd992f4280692f160e1ef08b60bf39"

[[files]]
file = "mods/macaws-bridges.pw.toml"
hash = "ef3f71f992c06db063797fef0fcc16143cb48e90d069918f0767e3e0ecf560df"
metafile = true

[[files]]
file = "mods/macaws-doors.pw.toml"
hash = "88e28dcf21277be5381110796df15d6c897e402fee1ebdccfa3fa57a9e957dce"
metafile = true

[[files]]
file = "mods/macaws-fences-and-walls.pw.toml"
hash = "4027de0259ae439ccfa55e1e2a825b22f95f6bb99ef0792c420f6cf3c0b346a1"
metafile = true

[[files]]
file = "mods/macaws-furniture.pw.toml"
hash = "b0e06af556a13d39f0f6cb9014ecee087ec027933a25901f52933d6505a7406a"
metafile = true

[[files]]
file = "mods/macaws-holidays.pw.toml"
hash = "f5e8d5b8da46a01d7b3073c9cbab5a29df11438c4b9af981867dc41c6b153429"
metafile = true

[[files]]
file = "mods/macaws-lights-and-lamps.pw.toml"
hash = "03248dc1fd80eaae2ba009f0d38a88e02c83a4cc01983fbfc5a01e0631e11969"
metafile = true

[[files]]
file = "mods/macaws-paintings.pw.toml"
hash = "347f3e885eeafe50a4824c21dd211ccc2198f55d0e93ec0118c4b0b6ca065d71"
metafile = true

[[files]]
file = "mods/macaws-paths-and-pavings.pw.toml"
hash = "1e351be3ac26846f922568c1a447d0a6afecad3979bd796cff41de011178e1ec"
metafile = true

[[files]]
file = "mods/macaws-stairs.pw.toml"
hash = "a16a348923210f7c025dd4bf23cfab3f8f1f958673fb3d3ed1bcdc3466f95204"
metafile = true

[[files]]
file = "mods/macaws-windows.pw.toml"
hash = "d530eb4b3820c20855f3c332e77c11c3cd6d66b41f3e77871dbd71646d9a222a"
metafile = true

[[files]]
file = "mods/malilib.pw.toml"
hash = "dd766c9ebeaf93db8b869f6bcaa83a07040a1413e5171be0577dd9a3dd8d3b04"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
hash = "7c702d1eb46d5c70af78a3414e1a29e610b73975d5ba3826e1bfdb89c3857b39"
metafile = true

[[files]]
file = "mods/monolib.pw.toml"
hash = "78edb60c5f000117cb45401be6b3701963d39b79aa9d43043496ac8fc7be5be0"
metafile = true

[[files]]
file = "mods/mouse-tweaks.pw.toml"
hash = "3cd8155341a4233955ff9892a3b7b5da6dc6d8d892863b2f544328f2731f7f03"
metafile = true

[[files]]
file = "mods/oceans-delight.pw.toml"
hash = "cf54f809005413bf720687a44782c101b54f1555684403080b3c06033634e9c4"
metafile = true

[[files]]
file = "mods/owo-lib.pw.toml"
hash = "59f3b2e1679e710e694b04e712b2f79be11ec4f1591d831c3adaa86e16d0c1ef"
metafile = true

[[files]]
file = "mods/pick-up-notifier.pw.toml"
hash = "d72ceecfc2e90f621c62d17da93730851295076aad564b877f56c73b590856f7"
metafile = true

[[files]]
file = "mods/polymorph.pw.toml"
hash = "4450b4162b40ff483495103ed9646d5b65e8652876495b084473cfc7e29ece5a"
metafile = true

[[files]]
file = "mods/puzzles-lib.pw.toml"
hash = "417736a881b0b5f7ff50f0c7874532ca386314752d44e0ef1377bbb1dfe9d33d"
metafile = true

[[files]]
file = "mods/reacharound.pw.toml"
hash = "fa0c5f3f503c9bd018dc289b485d18e61551da0c3a9775dfca2fe6923424b7d4"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "2494505990ebe04a740fbae936efdf4d24a52071c04d3b73d215b9539e59817b"
metafile = true

[[files]]
file = "mods/refurbished-furniture.pw.toml"
hash = "7ceada6e6fdfb868c17a2d2212cb3b494150fa5717d653605464176f3e4c65de"
metafile = true

[[files]]
file = "mods/resourceful-config.pw.toml"
hash = "3ce0ab5d205fc7e63684e99cfd62ac905a4cf8ff980adbd798b08b7c7ba98a8e"
metafile = true

[[files]]
file = "mods/resourceful-lib.pw.toml"
hash = "8deb4040131569c97902b40e0d81ef80330c6bb477c2ebcf5a5d987e1348eb96"
metafile = true

[[files]]
file = "mods/rightclickharvest.pw.toml"
hash = "6f039f474f01f1991e1515fc44898679058a425bda5c784d70227fe610bf643b"
metafile = true

[[files]]
file = "mods/ring-of-the-enderchest-fabric.pw.toml"
hash = "02e36c927b764dd9f70e72983e052488854ee02045a94a6c34df30616748d191"
metafile = true

[[files]]
file = "mods/selene.pw.toml"
hash = "f4b6a5ff4f63aad21fb0de3165e9dd3f2186fe70f9ae06e663e28b30a75ae4e8"
metafile = true

[[files]]
file = "mods/sodium-options-api.pw.toml"
hash = "faa58868fad174ceb591284edd09d114648a2fc69247bea6506cc3ced1399c7b"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "f73a48751e13380b87296e5b9627c9f6669efda386bd646fd5c499b344570f46"
metafile = true

[[files]]
file = "mods/supplementaries.pw.toml"
hash = "d2613d3b3a6e033dc5c7772ce4f2391ff04e802d891a0d4ce23819ef918b6783"
metafile = true

[[files]]
file = "mods/terrablender-fabric.pw.toml"
hash = "e86c6f0670536421a538e1bee2c8ce904bf89d31eb311eb9ee8c344cc849aa9c"
metafile = true

[[files]]
file = "mods/trade-cycling.pw.toml"
hash = "018f389149c9cb3f2a280a3e55537776951ee56886501cc3e0ae7c2e6f1a3aae"
metafile = true

[[files]]
file = "mods/trading-post.pw.toml"
hash = "4d276107495fe870f5d302339e9890ccee9ae52da936dd02145f660d20c55765"
metafile = true

[[files]]
file = "mods/trashslot.pw.toml"
hash = "db272744a92c1392cce55a0da903016f05e9c53f7e11a5582309fbfa9b1a72b5"
metafile = true

[[files]]
file = "mods/travelers-backpack-fabric.pw.toml"
hash = "cac589fc1029786ab633000a3b122f3ab74403780007b197a37982e29976a0fd"
metafile = true

[[files]]
file = "mods/trinkets.pw.toml"
hash = "7b5e8074a47ad6a9e453a29853bb1527906ae0ced0d714fcd386c75ef1f0f00a"
metafile = true

[[files]]
file = "mods/visual-workbench.pw.toml"
hash = "5565b1bf1638907ea181655350d9edd6d0d016e3cdc49b7cbd890fac88448a56"
metafile = true

[[files]]
file = "mods/what-are-they-up-to.pw.toml"
hash = "bbe626ae5e123ad07ad82ac39b94bbe2f9c8fc13513f9907e01115ba0cd5b40f"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "ed0e142a87ebbae7caa0c8311002a2d4e33766bcccf7ee6637ec5308a42eeb5c"
metafile = true

[[files]]
file = "mods/zoomify.pw.toml"
hash = "1836c4b896229b4283d28009951c913b518df7aefd0ccb05f12cd954c3a7deb8"
metafile = true

[[files]]
file = "resourcepacks/MandalasGUI+Dakmode_1.21.6_v2.0.zip"
hash = "b78848fbd262136b0375aa992e8d8208e8ecc3d1eb0e0c267778151c5ded2659"

[[files]]
file = "resourcepacks/Stay Clear V1.1 [1.21.1].zip"
hash = "8f708c91f0b38a9c3b5ca0f9039f093912a03b4b44bf95249618a729dc8a7565"

[[files]]
file = "shaderpacks/ComplementaryReimagined_r5.6.1.zip"
hash = "33153747d25fbee470acb42ccf4f26b03cc551bb900d4c6d3389b5500dd84839"

[[files]]
file = "shaderpacks/ComplementaryUnbound_r5.6.1.zip"
hash = "1c25b2b917ff6d0a511cf2edd8992e0bc66c950c401020f1b0362646bb3e2952"
