name = "OhanaFab"
author = "Yahia"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6dc2f6d81a3ead6c9e049d5c8d93b69cf5ed5f68e8ce1735c1c70a380b6a9bb1"

[versions]
fabric = "0.17.3"
minecraft = "1.21.1"
