name = "OhanaFab"
author = "Yahia"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9898e59d6a94b3408031dd1e812f36243873fc1a44d6f91d2c9475e60ec0a21a"

[versions]
fabric = "0.17.3"
minecraft = "1.21.1"
