name = "OhanaFab"
author = "Yahia"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6915b4b4fd5f42526407c59efef5b4342dca5754a58724daac9e34798508d90c"

[versions]
fabric = "0.17.3"
minecraft = "1.21.1"
